---
date: "25/02/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE, comment="")

rm(list=ls())
library(rmarkdown)
library(kableExtra)
```

### BREAKPOINT on TP
```{r}

#read in data supplied by DFO, rename and aggregate into annuual means
library(openxlsx)

my_data <-(as.data.frame(read.csv("E:/homeoffice/kim/Quinte/Quinte2022.csv")))
#rename col in recent file
colnames(my_data)[1]<-"Station_Acronym"
colnames(my_data)[colnames(my_data)=="Kd"] <- "epar"
colnames(my_data)[colnames(my_data)=="Secchi"] <- "secchi"
colnames(my_data)[colnames(my_data)=="chl"] <- "Chla"

colnames(my_data)[colnames(my_data)=="TotalPhyto"]<-"Phyto_BM"

mmetric="epar" #select which metric to analyze
#mlab=expression(Light~attenuation~(m^-1)) 
#mlab=expression(Chlorophyll~a~(mu~g~L^-1))
mlab=expression(Total~phosophorus~(mg~L^-1))


#sscal=1.25 #clorophyll and round 1
sscal=1. #clorophyll and round 1
sscal=0.01 #clorophyll and round 1
#aggregate and run analysis on selected sites
frm=paste(mmetric,"~ Station_Acronym+year")
spydat=aggregate(as.formula(frm), my_data, length)
mdat=aggregate(as.formula(frm), my_data, mean)
colnames(spydat)[3]="n"
spydat[4]=mdat[3]
colnames(spydat)[4]="metric"
spydat$weights <- spydat$n/mean(spydat$n)


agg <- aggregate(list(metric=my_data[mmetric],TP=my_data$TP), 
                 by = list(Station_Acronym=my_data$Station_Acronym, year=my_data$year), 
                 FUN=mean, na.rm=TRUE, na.action="na.pass")
agg2 <- aggregate(list(metricN=my_data[mmetric]), 
                  by = list(Station_Acronym=my_data$Station_Acronym, year=my_data$year), 
                  FUN=length)
agg$n=agg2[,3]
agg$weights <- agg$n/mean(agg$n)
colnames(agg)[3]="metric"
colnames(agg)[4]="TP"

#select sites on which to run analysis
stvec=c("B", "HB",  "C")

stlabel=c("Belleville", "Hay Bay", "Conway")
#select sites on which to run analysis

par(mfrow=c(3,2), mar=c(0,4,0,3), oma=c(5,5,2,2),cex.axis=1.25)


spydat=agg[agg$Station_Acronym%in%stvec,]

xyear=c(1972,2008)
spydat=spydat[spydat$year%in%c(1972:2008),]
spydat$Station_Acronym=as.factor(spydat$Station_Acronym)
#str(spydat)

#rm(list=ls())
library(strucchange)




site=stvec
bxlab=c("","", "Breaks")
bylab=c("","BIC", "")
ly=expression(paste("Light Attentuated (", m^-1, ")"))
lylab=c("", ly, "")


#TP model
tp1=(lm(TP~year:Station_Acronym, weights=weights, data=spydat))
tp2=(lm(TP~year+Station_Acronym, weights=weights, data=spydat))
tp3=(lm(TP~year:Station_Acronym+Station_Acronym, weights=weights, data=spydat))





cop=AIC(tp1,tp2,tp3)
cop
m1=which.min(cop$AIC)
mod=row.names(cop)[m1]
bestmod=as.name(mod)
#summary(eval(bestmod))

```
A model with site-specific slopes and intercepts, was preferred ((AIC=`r cop[3,2]`, $R^2$=`r summary(tp3)$adj.r.squared`) over a model with global slope, but site specific intercepts (AIC=`r cop[1,2]`, $R^2$=`r summary(tp1)$adj.r.squared`) and models with site specific slopes but global intercepts (AIC=`r cop[2,2]`, $R^2$=`r summary(tp2)$adj.r.squared`).


```{r}
mpred=as.data.frame(predict(tp2, spydat, interval="confidence"))

spydat=cbind(spydat, mpred)

#spydat$tres=spydat$TP-spydat$tmodel
par(mfrow=c(3,1), mar=c(1,4,0,3), oma=c(5,5,2,2),
    cex.axis=1, cex.lab=1.75, cex.main=1.2, cex.sub=1)
for (i in 1:length(stvec)) {
  pdat=spydat[spydat$Station_Acronym==stvec[i],]
  
  mscale=c(min(pdat$TP, na.rm=TRUE)-sscal,
           max(pdat$TP, na.rm=T)+sscal)
  amscale=mscale
  mss=which(!complete.cases(pdat))
  if (length(mss)>0) pdat=pdat[-mss,]
  if (i==3) {
 
  amscale[2]=mscale[2]/3
  }
ymax=round(max(pdat$TP, na.rm=T),2)
plot(TP~year, data=pdat, type="b",xaxt="n",pch=16,col="grey",
     ann=FALSE, xlim=xyear, ylim=c(0,ymax+0.01), las=2, yaxp=c(0,ymax,3))

if ( i==3)axis(side=1, las=1)
legend("bottomleft",stlabel[i], bty="n",
       cex=1.5)

lines(pdat$fit~pdat$year, col = 2, lwd=2)
lines(pdat$lwr~pdat$year, col = "pink", lwd=2, lty=2)
lines(pdat$upr~pdat$year, col = "pink", lwd=2, lty=2)
}

treg=as.data.frame(summary(tp2)$coefficients)


sigstar=ifelse (treg[,4]<0.5, "*", "") 
 treg[,4]=formatC(treg[,4], format = "e", digits = 1)
 treg[,4]=paste(treg[,4],sigstar)





regco=kable(treg, digits=5,
            #format="html", table.attr = "style='width:60%;'",
   caption="TP~year")
tsave=footnote(kable_classic(regco),
         general = paste("adj. R squared=", round((summary(tp2)$adj.r.squared),2)),
         footnote_as_chunk = TRUE,
         general_title = "")
tsave
#fname=paste0(mmetric,"Site", stvec[i],".png")
#print(tsave)
#cat('\n\n<!-- -->\n\n')



```

```{r}
reglist=list()
 regnolist=list()
#tiff('baseR_figure.tiff', width =85, 
#     height = 180, pointsize = 12,
#     units = 'mm', res = 300)

#jpeg('baseR_figure.jpeg', width =85, 
#     height = 180,
#     units = 'mm', pointsize = 12,
#     quality = 75,
#     res = 300)

par(mfrow=c(3,1), mar=c(0.5,3,1,1), oma=c(4,3,0,0),
    cex.axis=1.2, cex.lab=1.75, cex.main=1.2, cex.sub=1)
for (i in 1:length(stvec)) {

  pdat=spydat[spydat$Station_Acronym==stvec[i],]
  dat=ts(spydat$TP[spydat$Station_Acronym==site[i]], start=spydat$year[1], 
         end=spydat$year[length(spydat$year)])
  tt=1:length(dat)
  mss=which(!complete.cases(pdat))
  if (length(mss)>0) pdat=pdat[-mss,]
  
  #b=breakpoints(dat~1)
  b=breakpoints(TP ~ year, data=pdat)
  #b=breakpoints(metric ~ year, data=pdat)
  print(b)
cat('\n\n<!-- -->\n\n')
  if (sum(!is.na(b$breakpoints))>0){
  
  # fit segmented model
  fac.ri <- breakfactor(b, label = "seg")
#   if (length(mss)>0){
#  bfac.ri=fac.ri[1:(mss-1)]
#  bfac.ri=c(bfac.ri, NA)
#  bfac.ri=c(bfac.ri, fac.ri[(mss):length(fac.ri)])
#   }else{
#     bfac.ri= fac.ri
  
  
  time=as.factor(fac.ri)
  fm.riT2 <- lm(TP ~ time:year+time, data=pdat, weights=weights)
  fm.riT <- lm(TP ~ time:year, data=pdat, weights=weights)
  fm.ri <- lm(TP ~ time+year, data=pdat, weights=weights)
  fm.riN <- lm(TP ~ year, data=pdat,weights=weights)
  sc=(AIC(fm.ri, fm.riN,fm.riT, fm.riT2))
  print(sc)
  bm=which.min(sc[,2])
  fm.ri=fm.ri
  } else {
    fm.ri <- lm(TP ~ year, data=pdat,weights=weights)
  }
  
  #table of output
  fm.no<- lm(TP ~ year, data=pdat,weights=weights)
reglist[[i]]=fm.ri  
  regnolist[[i]]=fm.no
#summary(fm.ri)$adj.r.squared


  amscale=mscale
  amscale=c(0, 0.1)
  if (i==3) amscale[2]=amscale[2]/2
  plot(TP~year, data=pdat, type="b",xaxt="n",pch=16,col="grey",
      # ann=FALSE, 
       xlim=xyear, ylim=amscale,las=2,yaxp=c(0,round(0.1,2),4))
  
  if ( i==3)axis(side=1, las=1)
  legend("topright",stlabel[i], bty="n",
         cex=1.5)

  bfm=predict( fm.ri, newdata=pdat)
  
  lines(bfm~pdat$year, col = 2, lwd=2)

  
  #convert confidence intervals from julian day to dates
  #and draw
  
  #draw breakpoints & confidence intervals 
 if (sum(!is.na(b$breakpoints))>0){
  cis=confint(b)$confint
  cll=cis[summary(fm.ri)$coefficients[2:(1+length(b$breakpoints)),4]<1.,]
   ci=cis[summary(fm.ri)$coefficients[2:(1+length(b$breakpoints)),4]<0.05,]
   if (length(nrow(cll))!= 0) {
  if (nrow(cll)== 1) abline(v=pdat$year[cll[2]], lty=2, col="light grey")
   if (nrow(cll)>1) abline(v=pdat$year[cll[,2]], lty=2, col="light grey")
   }
  hgt=amscale[2]-0.005
  if(i==3) hgt=hgt/2
  
#  if (i==3) hgt=4
  tm=nrow(ci)
  if (length(tm)==0) {
      tm=1 
    } else if (tm==0)  {
      tm=1
    }
  yn=rep(hgt,tm)
  
  if (tm==1) {
    s=1
    xn=pdat$year[ci[1]]
    xx=pdat$year[ci[3]]
    yx=yn
    segments(xn[s], yn[s], xx[s], yx[s], col="blue", lwd=2, lend="square")
    text(pdat$year[ci[2]]-2.5,y=amscale[2]-.001, pdat$year[ci[2]])
   
    abline(v=pdat$year[ci[2]], lty=2, col="blue")
  } else {
    yn=rep(hgt,tm)
    
  s=1:tm
  
  xn=pdat$year[ci[,1]]
  xx=pdat$year[ci[,3]]
  yx=yn
  segments(xn[s], yn[s], xx[s], yx[s], col="blue", lwd=2, lend="square")

 
     abline(v=pdat$year[ci[,2]], lty=2, col="blue")
  text(pdat$year[ci[,2]]-2.5,y=amscale[2]-.001, pdat$year[ci[,2]])
  }

 }
  
  mtext(mlab, side = 2, line = +1, outer = TRUE, at = NA,
        adj = NA, padj = NA, cex = 1.4, col = NA, font = NA)
  mtext("year", side = 1, line = +2, outer = TRUE, at = NA,
        adj = NA, padj = NA, cex = 1.4, col = NA, font = NA)
  

}
legend("topleft", c("data", "model", "breakpoint",
                  "breakpoint CI"), ncol=2,
       lty=c(1,1,2,1), col=c("grey", "red","blue", "blue"), 
       pch=c(16,NA,NA,NA),
       bty="n", cex=1.2)
#dev.off()

##########END BREAKPOINT
```


```{r}
i=1
regs=as.data.frame(summary(reglist[[i]])$coefficients) 
sigstar=ifelse (regs[,4]<0.05, "*", "") 
 regs[,4]=formatC(regs[,4], format = "e", digits = 1)
 regs[,4]=paste(regs[,4],sigstar)




 rsq=round((summary(reglist[[i]])$adj.r.squared),4)
 regn=as.data.frame(summary(regnolist[[i]])$coefficients)
 sigstar=ifelse (regn[,4]<0.5, "*", "") 
 regn[,4]=formatC(regn[,4], format = "e", digits = 1)
 regn[,4]=paste(regn[,4],sigstar)
 
 regout=list(regs,regn)
regco=kable((regout), digits=4,
            #format="html", table.attr = "style='width:60%;'",
   caption=paste("TP","Site", stvec[i]))
sics=AIC(reglist[[i]],regnolist[[i]])
model=as.character(c(reglist[[i]]$call, regnolist[[i]]$call))
tabtext=data.frame(model=model,
  AIC=sics[,2], Rsq=c(rsq,summary(regnolist[[i]])$adj.r.squared))

tsave=footnote(kable_classic(regco),
        # general = paste("adj. R squared=",rsq),
        general=c(tabtext[1,],tabtext[2,]),
         footnote_as_chunk = FALSE,
         general_title = "")

#fname=paste0(mmetric,"Site", stvec[i],".png")
tsave

```

```{r}
i=2

regs=as.data.frame(summary(reglist[[i]])$coefficients) 
sigstar=ifelse (regs[,4]<0.05, "*", "") 
 regs[,4]=formatC(regs[,4], format = "e", digits = 1)
 regs[,4]=paste(regs[,4],sigstar)




 rsq=round((summary(reglist[[i]])$adj.r.squared),4)
 regn=as.data.frame(summary(regnolist[[i]])$coefficients)
 sigstar=ifelse (regn[,4]<0.5, "*", "") 
 regn[,4]=formatC(regn[,4], format = "e", digits = 1)
 regn[,4]=paste(regn[,4],sigstar)
 regout=list(regs,regn)
regco=kable((regout), digits=4,
            #format="html", table.attr = "style='width:60%;'",
   caption=paste("TP","Site", stvec[i]))
sics=AIC(reglist[[i]],regnolist[[i]])
model=as.character(c(reglist[[i]]$call, regnolist[[i]]$call))
tabtext=data.frame(model=model,
  AIC=sics[,2], Rsq=c(rsq,summary(regnolist[[i]])$adj.r.squared))

tsave=footnote(kable_classic(regco),
        # general = paste("adj. R squared=",rsq),
        general=c(tabtext[1,],tabtext[2,]),
         footnote_as_chunk = FALSE,
         general_title = "")

#fname=paste0(mmetric,"Site", stvec[i],".png")
tsave

```

```{r}
i=3
regs=as.data.frame(summary(reglist[[i]])$coefficients) 
sigstar=ifelse (regs[,4]<0.05, "*", "") 
 regs[,4]=formatC(regs[,4], format = "e", digits = 1)
 regs[,4]=paste(regs[,4],sigstar)




 rsq=round((summary(reglist[[i]])$adj.r.squared),4)
 regn=as.data.frame(summary(regnolist[[i]])$coefficients)
 sigstar=ifelse (regn[,4]<0.5, "*", "") 
 regn[,4]=formatC(regn[,4], format = "e", digits = 1)
 regn[,4]=paste(regn[,4],sigstar)
 regout=list(regs,regn)
regco=kable((regout), digits=4,
            #format="html", table.attr = "style='width:60%;'",
   caption=paste("TP","Site", stvec[i]))
sics=AIC(reglist[[i]],regnolist[[i]])
model=as.character(c(reglist[[i]]$call, regnolist[[i]]$call))
tabtext=data.frame(model=model,
  AIC=sics[,2], Rsq=c(rsq,summary(regnolist[[i]])$adj.r.squared))

tsave=footnote(kable_classic(regco),
        # general = paste("adj. R squared=",rsq),
        general=c(tabtext[1,],tabtext[2,]),
         footnote_as_chunk = FALSE,
         general_title = "")

#fname=paste0(mmetric,"Site", stvec[i],".png")
tsave
#save_kable(tsave,file=fname, density=600, zoom = 1.25, bs_theme = "flatly")


```
