---
title: "Untitled"
author: "Kim Cuddington"
date: "11/02/2022"
 
output:
  word_document: default
  html_document: default
  
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#rmarkdown::render("gamtablesres.Rmd") to use previously calcluated
#rmarkdown::render("gamtablesres.Rmd", output_format="all")
library(rmarkdown)
library(kableExtra)
```

## BREAKPOINT
```{r}
 
  #table of output
summary(frl)$adj.r.squared
options("scipen"=2, "digits"=2)
regout=(summary(frl)$p.table)
row.names(regout)=c("Intercept (B)", "C", "HB")
regout=as.data.frame(regout)
regout[,4]=formatC(regout[,4], format = "e", digits = 1)



sregout=summary(frl)$s.table
row.names(sregout)=c("s(year):B", "s(year):C","s(year):HB")
sregout=as.data.frame(sregout)
sregout[,4]=formatC(sregout[,4], format = "e", digits = 1)


dataframe_list=list(regout, sregout)




regco=kable((dataframe_list),
            #format="html", table.attr = "style='width:80%;'",
   caption="Light attenuation")
regco
tsave=footnote(kable_classic(regco),
         general = paste("deviance explained=", round(summary(frl)$dev.expl,2)),
         footnote_as_chunk = TRUE,
         general_title = "")


tsave
```


```{r}
 
  #table of output
summary(frc)$adj.r.squared
options("scipen"=2, "digits"=2)
regout=(summary(frc)$p.table)
row.names(regout)=c("Intercept (B)", "C", "HB")
regout=as.data.frame(regout)
regout[,4]=formatC(regout[,4], format = "e", digits = 1)



sregout=summary(frc)$s.table
row.names(sregout)=c("s(year):B", "s(year):C","s(year):HB")
sregout=as.data.frame(sregout)
sregout[,4]=formatC(sregout[,4], format = "e", digits = 1)


dataframe_list=list(regout, sregout)




regco=kable((dataframe_list),
            #format="html", table.attr = "style='width:80%;'",
   caption="Chlorophyll a")
regco
tsave=footnote(kable_classic(regco),
         general = paste("deviance explained=", round(summary(frc)$dev.expl,2)),
         footnote_as_chunk = TRUE,
         general_title = "")


tsave
```
```{r}
 
  #table of output
summary(mc)$adj.r.squared
options("scipen"=2, "digits"=2)
regout=(summary(mc)$p.table)
#row.names(regout)=c("Intercept (B)", "C", "HB")
regout=as.data.frame(regout)
regout[,4]=formatC(regout[,4], format = "e", digits = 1)



sregout=summary(mc)$s.table
#row.names(sregout)=c("s(year):B", "s(year):C","s(year):HB")
sregout=as.data.frame(sregout)
sregout[,4]=formatC(sregout[,4], format = "e", digits = 1)


dataframe_list=list(regout, sregout)




regco=kable((dataframe_list),
            #format="html", table.attr = "style='width:80%;'",
   caption="Chlorophyll a")
regco
tsave=footnote(kable_classic(regco),
         general = paste("deviance explained=", round(summary(mc)$dev.expl,2)),
         footnote_as_chunk = TRUE,
         general_title = "")


tsave
```
```{r}

  #table of output
summary(ml)$adj.r.squared
options("scipen"=2, "digits"=2)
regout=(summary(ml)$p.table)
#row.names(regout)=c("Intercept (B)", "C", "HB")
regout=as.data.frame(regout)
regout[,4]=formatC(regout[,4], format = "e", digits = 1)



sregout=summary(ml)$s.table
#row.names(sregout)=c("s(year):B", "s(year):C","s(year):HB")
sregout=as.data.frame(sregout)
sregout[,4]=formatC(sregout[,4], format = "e", digits = 1)


dataframe_list=list(regout, sregout)




regco=kable((dataframe_list),
            #format="html", table.attr = "style='width:80%;'",
   caption="Light attenuation")
regco
tsave=footnote(kable_classic(regco),
         general = paste("deviance explained=", round(summary(ml)$dev.expl,2)),
         footnote_as_chunk = TRUE,
         general_title = "")


tsave
```

fname=paste0(mmetric,"Site", stvec[i],".png")


#save_kable(tsave,file=fname, density=600, zoom = 1.25, #bs_theme = "flatly")

```
