---
date: "25/02/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
#rmarkdown::render("gamtables.Rmd") to use previously calcluated

library(rmarkdown)
library(kableExtra)
```

### Full Gam
```{r, echo=FALSE}
 
  #table of output

options("scipen"=2, "digits"=2)
regout=(summary(fm)$p.table)
row.names(regout)=c("Intercept (B)", "C", "HB")
regout=as.data.frame(regout)

sigstar=ifelse (regout[,4]<0.05, "*", "") 
regout[,4]=formatC(regout[,4], format = "e", digits = 1)
regout[,4]=paste(regout[,4],sigstar)






sregout=summary(fm)$s.table
row.names(sregout)=c("s(TP)", "s(year):B", "s(year):C","s(year):HB")
sregout=as.data.frame(sregout)
sigstar=ifelse (sregout[,4]<0.05, "*", "") 
sregout[,4]=formatC(sregout[,4], format = "e", digits = 5)
sregout[,4]=paste(sregout[,4],sigstar)


dataframe_list=list(regout, sregout)




regco=kable((dataframe_list),format="html", table.attr = "style='width:80%;'",
   caption="Light attenuation")
#regco
tsave=footnote(kable_classic(regco),
         general = paste("deviance explained=", round(summary(fm)$dev.expl,2)),
         footnote_as_chunk = TRUE,
         general_title = "")


tsave

condf=as.data.frame(round(concurvity(fm, full=FALSE)$worst,2))
row.names(condf)=c("linear", "s(TP)", "s(year):B", "s(year):C","s(year):HB")
colnames(condf)=c("linear", "s(TP)", "s(year):B", "s(year):C","s(year):HB")
contab=kable((condf[-1,-1]),format="html", table.attr = "style='width:80%;'",
   caption="Light attenuation: concurvity")

kable_classic(contab)


tpreg=summary(fmred)$coefficients

```


```{r, echo=FALSE}
 
  #table of output

options("scipen"=2, "digits"=2)
regout=(summary(fc)$p.table)
row.names(regout)=c("Intercept (B)", "C", "HB")
regout=as.data.frame(regout)

sigstar=ifelse (regout[,4]<0.05, "*", "") 
regout[,4]=formatC(regout[,4], format = "e", digits = 1)
regout[,4]=paste(regout[,4],sigstar)




sregout=summary(fc)$s.table
row.names(sregout)=c("s(TP)", "s(year):B", "s(year):C","s(year):HB")
sregout=as.data.frame(sregout)
sigstar=ifelse (sregout[,4]<0.05, "*", "") 
sregout[,4]=formatC(sregout[,4], format = "e", digits = 5)
sregout[,4]=paste(sregout[,4],sigstar)


dataframe_list=list(regout, sregout)




regco=kable((dataframe_list),format="html", table.attr = "style='width:80%;'",
   caption="Chlorophyll a")
#regco
tsave=footnote(kable_classic(regco),
         general = paste("deviance explained=", round(summary(fc)$dev.expl,2)),
         footnote_as_chunk = TRUE,
         general_title = "")


tsave

rm(condf)
condfc=as.data.frame(round(concurvity(fc, full=FALSE)$worst,2))
row.names(condfc)=c("linear", "s(TP)", "s(year):B", "s(year):C","s(year):HB")
colnames(condfc)=c("linear", "s(TP)", "s(year):B", "s(year):C","s(year):HB")
contabc=kable((condfc[-1,-1]),format="html", table.attr = "style='width:80%;'",
   caption="Chlorophyll a: concurvity")

kable_classic(contabc)

```

```{r}
modsum=as.data.frame(fcvec)
modsum$lightAIC=sc
modsum$ChlorAIC=scc
colnames(modsum)=c("model", "AIC(light)", "AIC(chlorophyll)")
contabm=kable(modsum,
              #format="html", table.attr = "style='width:80%;'",
   caption="Models evaluated")
kable_classic(contabm)
```
