---
date: "25/02/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
#rmarkdown::render("TPgamtables.Rmd") to use previously calcluated

library(rmarkdown)
library(kableExtra)
```

### Full Gam
```{r, echo=FALSE}
 
  #table of output

options("scipen"=2, "digits"=4)
regout=as.data.frame(summary(fm)$p.table)

sigstar=ifelse (regout[,4]<0.05, "*", "") 
regout[,4]=formatC(regout[,4], format = "e", digits = 2)
regout[,4]=paste(regout[,4],sigstar)



row.names(regout)=c("Intercept (B)", "C", "HB")





sregout=as.data.frame(summary(fm)$s.table)
row.names(sregout)=c("s(year):B", "s(year):C","s(year):HB")
sregout=as.data.frame(sregout)
ssigstar=ifelse (sregout[,4]<0.05, "*", "") 
sregout[,4]=formatC(sregout[,4], format = "e", digits = 2)
sregout[,4]=paste(sregout[,4],ssigstar)


dataframe_list=list(regout, sregout)




regco=kable((dataframe_list),format="html", table.attr = "style='width:80%;'",
   caption="Total phosphorus")
#regco
tsave=footnote(kable_classic(regco),
         general = paste("deviance explained=", round(summary(fm)$dev.expl,2)),
         footnote_as_chunk = TRUE,
         general_title = "")


tsave



```

```{r}
smooth_estimates(fm)
yearfit=predict(fm, newdata=pdat, se.fit=TRUE)
pdat$yrfit=yearfit$fit
pdat$yrse=yearfit$se

mscale=c(0,
         max(pdat$upper, na.rm=T)+sscal)
#####

###tiff('baseR_figure.tiff', width =130, 
   ##  height = 80, pointsize = 12,
    ## units = 'mm', res = 300)

###jpeg('baseR_figure.jpeg', width =130,height = 80,
    ## units = 'mm', pointsize = 12,
     ##quality = 75,
     ##res = 300)

panlab=c("(a)","(b)","(c)","(d)","(e)","(f)","(g)","(h)","(j)", "(i)" )


par(mfcol=c(3,2), mar=c(0.5,4,1,1), oma=c(4,1,0,0),
    cex.axis=1.1, cex.lab=1.75, cex.main=1.2, cex.sub=1)
for (i in 1:3){
  ylim1=c(0.5,2.25)
  if (i==3) ylim1=ylim1/2
  datre=pdat[pdat$Station_Acronym==stvec[i],]
  plot(metric~year, xaxt="n",pch=16, data=datre,bty='l',cex=.8,
       ann=FALSE,  xlim=c(1972.5,2007.5),ylim=ylim1,las=2)
  lines(fitted~year, lwd=2,data=datre,col=1)
# lines(upper~year, data=datre,col="purple")
#  lines(lower~year, data=datre,col="purple")
  x=c(rev(datre$lower), datre$upper)
  y=c(rev(datre$year), datre$year)
  polygon(y,x, col=adjustcolor("grey",alpha.f=0.3), border=NA )
  legend("topright",panlab[i], bty="n",
         inset=c(0.07,0), 
         cex=1.2)
#  text(y=35, x=1990,stlabel[i], bty="n",
 #      cex=1.25 )
 # title(stlabel[i], cex=0.8)
  mtext(stlabel[i], side = 3, line = -1, outer = FALSE, at = NA,
        adj = NA, padj = NA, cex = 1.2, col = NA, font = NA)
  if ( i==3)axis(side=1, las=1)
}
mtext(mlab, side = 2, line = -1.5, outer = TRUE, at = NA,
      adj = NA, padj = NA, cex = 1.1, col = NA, font = NA)
mtext("year", side = 1, line = +2, outer = TRUE, at = NA,
      adj = NA, padj = NA, cex = 1.4, col = NA, font = NA)

pout=partial_residuals(fm, select = "s(year)", partial_match=TRUE)
sout=smooth_estimates(fm, smooth = "s(year)", partial_match=TRUE)
pout=pout[,c(1,3,2)]
# or selected smooths
dfsm=edf(fm, smooth = colnames(pout))
dfsm=as.data.frame(dfsm)
drt[[2]]$p.resid

colnames(pout)=c("s(year):B", "s(year):HB", "s(year):C")


dtall=as.data.frame(derivatives(fm, interval="simultaneous"))
dtall$smooth=as.factor(dtall$smooth)
dlit=split(dtall, dtall$smooth)

dseq=c(1,3,2)

for (j in seq_along(dseq)) {
  yaxl=c(-.07,.07)
  if (j==3) yaxl=yaxl/2
  i=dseq[j]
  dat=dlit[i]
  dat=as.data.frame(dlit[i])
  colnames(dat)=colnames(dtall)
  plot(derivative~data, data=dat,xaxt="n",ann=FALSE,bty='l',las=2,cex=1.2,
       ylim=yaxl, typ="l", lwd=2, col="dark red", xlim=c(1972.5,2007.5))
  lines(lower~data, data=dat, col="dark red")
  lines(upper~data, data=dat,col="dark red")
  x=c(rev(dat$lower), dat$upper)
  x[x>yaxl[2]]<-yaxl[2]+.01
  x[x< yaxl[1]]<-yaxl[1]-.01
  y=c(rev(dat$data), dat$data)
  polygon(y,x, col=adjustcolor("dark red",alpha.f=0.1), border=NA )
  
  abline(h=0, col="dark grey", lwd=2)
  abline(v=1994, col="dark grey", lwd=2)
  if (j==3) text(1990, 0.025, "1994", cex=1.1)
  if (j==3)axis(side=1, las=1)
  if (j==2) mtext("Derivative of smooth", side = 2, line = 3.25, outer = FALSE, at = NA,
                  adj = NA, padj = NA, cex = 1.1, col = NA, font = NA)
  legend("topright",panlab[i+3], bty="n",
         inset=c(0.07,0), 
         cex=1.2)
  
}
```
